export const Channels = {
  SOURCES_LIST: 'sources:list',
  RECORDING_START: 'recording:start',
  RECORDING_STOP: 'recording:stop',
  RECORDING_PAUSE: 'recording:pause',
  RECORDING_STATUS: 'recording:status',
  CURSOR_DATA: 'cursor:data',
  EXPORT_START: 'export:start',
  EXPORT_PROGRESS: 'export:progress',
  EXPORT_DONE: 'export:done',
  PERMISSIONS_CHECK: 'permissions:check',
  PERMISSIONS_REQUEST: 'permissions:request',
  PERMISSIONS_CHANGED: 'permissions:changed',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SAVE: 'settings:save',
} as const
